# base image
FROM node:18

# set working directory
WORKDIR /app

# install dependencies
COPY package*.json ./
RUN npm install

# copy prisma schema BEFORE generating
COPY prisma ./prisma

# copy wait-for.sh
COPY scripts/wait-for.sh ./wait-for.sh
RUN chmod +x wait-for.sh

# copy source files
COPY . .

# generate prisma client
RUN npx prisma generate

# build app
RUN npm run build

# run app via wait-for script
CMD ["./wait-for.sh", "db", "npm", "run", "start:prod"]
